version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/patjacobs
permissions:
  - object: /var/www/patjacobs
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory

hooks:
  ApplicationStop:
    - location: deployment/production/scripts/application_stop/stop_pm2.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deployment/production/scripts/after_install/secrets_import.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deployment/production/scripts/application_start/start_pm2.sh
      timeout: 300
      runas: ubuntu
    - location: deployment/production/scripts/application_start/restart_nginx.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deployment/production/scripts/validate_service/curl_test.sh
      timeout: 300
      runas: root
