// global
export const PAGE_LOADED = 'PAGE_LOADED';
export const SPLASH_CHANGED = 'SPLASH_CHANGED';
export const TRANSPORT_CHANGED = 'TRANSPORT_CHANGED';
export const MENU_CHANGED = 'MENU_CHANGED';
export const MODE_CHANGED = 'MODE_CHANGED';
export const RECENT_WORK_TOP_SET = 'RECENT_WORK_TOP_SET';
